baseURL = "ba-amir.github.io"
languageCode = "en-us"
title = "Language Oriented"
theme = 'terminal'
description = "About literally anything that interests me really. So mostly programming language stuff"
